### PR TITLE
Fix A lot of notice non-object

### PR DESCRIPTION
**Pull request by Mte90**
I am getting this stuff in my log 
```
[14-May-2018 15:31:36 UTC] Array
(
    [error] => Notice
    [file] => /home/tksjdntw/skillsandmore.org/wp-content/plugins/social-warfare/functions/frontend-output/SWP_Buttons_Panel.php
    [line] => 103
    [context] => Array
        (
            [args] => Array
                (
                    [content] => 
                )

            [swp_social_networks] => Array
                (
                    [google_plus] => SWP_Google_Plus Object
                        (
                            [name] => Google Plus
                            [cta] => +1
                            [key] => google_plus
                            [default] => true
                            [premium] => 
                            [active] => 1
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => https://plus.google.com/share?url=
                            [show_shares] => 
                        )

                    [facebook] => SWP_Facebook Object
                        (
                            [name] => Facebook
                            [cta] => Condividi
                            [key] => facebook
                            [default] => true
                            [premium] => 
                            [active] => 1
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => http://www.facebook.com/share.php?u=
                            [show_shares] => 
                        )

                    [twitter] => SWP_Twitter Object
                        (
                            [name] => Twitter
                            [cta] => Tweet
                            [key] => twitter
                            [default] => true
                            [premium] => 
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => 
                            [show_shares] => 
                        )

                    [linkedin] => SWP_Linkedin Object
                        (
                            [name] => LinkedIn
                            [cta] => Condividi
                            [key] => linkedin
                            [default] => true
                            [premium] => 
                            [active] => 1
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => https://www.linkedin.com/cws/share?url=
                            [show_shares] => 
                        )

                    [pinterest] => SWP_Pinterest Object
                        (
                            [name] => Pinterest
                            [cta] => Pin
                            [key] => pinterest
                            [default] => true
                            [premium] => 
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => https://pinterest.com/pin/create/button/?url=
                            [show_shares] => 
                        )

                    [stumbleupon] => SWP_Stumble_Upon Object
                        (
                            [name] => StumbleUpon
                            [cta] => Stumble
                            [key] => stumbleupon
                            [default] => false
                            [premium] => 
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => http://www.stumbleupon.com/submit?url=
                            [show_shares] => 
                        )

                    [buffer] => SWP_Buffer Object
                        (
                            [name] => Buffer
                            [cta] => Buffer
                            [key] => buffer
                            [default] => false
                            [premium] => pro
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => http://bufferapp.com/add?url=
                            [show_shares] => 
                        )

                    [reddit] => SWP_Reddit Object
                        (
                            [name] => Reddit
                            [cta] => Reddit
                            [key] => reddit
                            [default] => 
                            [premium] => pro
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => https://www.reddit.com/submit?url=
                            [show_shares] => 
                        )

                    [flipboard] => SWP_Flipboard Object
                        (
                            [name] => Flipboard
                            [cta] => Flip
                            [key] => flipboard
                            [default] => 
                            [premium] => pro
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => https://share.flipboard.com/bookmarklet/popout?v=2&title=Tools%20-%20Flipboard&url=
                            [show_shares] => 
                        )

                    [email] => SWP_Email Object
                        (
                            [name] => Email
                            [cta] => Email
                            [key] => email
                            [default] => 1
                            [premium] => pro
                            [active] => 1
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => mailto:?subject=
                            [show_shares] => 
                        )

                    [hacker_news] => SWP_HackerNews Object
                        (
                            [name] => Hacker News
                            [cta] => Vote
                            [key] => hacker_news
                            [default] => 
                            [premium] => pro
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => http://news.ycombinator.com/submitlink?u=
                            [show_shares] => 
                        )

                    [pocket] => SWP_Pocket Object
                        (
                            [name] => Pocket
                            [cta] => Pocket
                            [key] => pocket
                            [default] => 
                            [premium] => pro
                            [active] => 1
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => https://getpocket.com/save?url=
                            [show_shares] => 
                        )

                    [tumblr] => SWP_Tumblr Object
                        (
                            [name] => Tumblr
                            [cta] => Condividi
                            [key] => tumblr
                            [default] => 
                            [premium] => pro
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => https://www.tumblr.com/widgets/share/tool?
                            [show_shares] => 
                        )

                    [whatsapp] => SWP_WhatsApp Object
                        (
                            [name] => WhatsApp
                            [cta] => WhatsApp
                            [key] => whatsapp
                            [default] => 
                            [premium] => pro
                            [active] => 1
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => whatsapp://send?text=
                            [show_shares] => 
                        )

                    [yummly] => SWP_Yummly Object
                        (
                            [name] => Yummly
                            [cta] => Yum
                            [key] => yummly
                            [default] => 
                            [premium] => pro
                            [active] => 
                            [html_store] => Array
                                (
                                )

                            [base_share_url] => http://www.yummly.com/urb/verify?url=
                            [show_shares] => 
                        )

                )

            [post] => 
        )

    [debug] => 
    [filter] => wp_footer
    [message] => Notice (8): Trying to get property of non-object
    [url] => https://domain/apple-touch-icon-precomposed.png
)```

The prupose of this fix is not to be executed the plugin if post type is not defined.

### CODE REVIEW

**Comment by Mte90** [comment]
This fix also the error that happen on 404 page and also for files that doens't exist that are redirect to the 404 page that generate an entry in the log.

**Comment by Mte90** [comment]
Update the pr with the latests changes.
I see also that the last release on github is 2.2.5 but on the readme is mentioned 3.0.0 but the last commit mention 3.0.7 https://github.com/warfare-plugins/social-warfare/commit/3755a3a21a3027b3199aec1628ac2d05c01547d0

So we cannot update in our website until a changelog is avalaible and also this pr is merged.

**Comment by Mte90** [comment]
I am getting today this in our log also if we are not using your widget (only the shortcode):
```
[16-May-2018 08:04:00 UTC] Array
(
    [error] => Notice
    [file] => /home/domain/wp-content/plugins/social-warfare/functions/widgets/SWP_Popular_Posts_Widget.php
    [line] => 362
    [context] => Array
        (
            [new_instance] => Array
                (
                    [title] => 
                    [count] => 6
                    [timeframe] => 0
                    [network] => totes
                    [showCount] => true
                    [countLabel] => Condivisioni
                    [thumbnails] => false
                    [thumb_size] => 100
                    [font_size] => 100
                    [style] => custom
                    [custom_bg] => #ffffff
                    [custom_link] => #000000
                )

            [old_instance] => Array
                (
                )

            [instance] => Array
                (
                    [title] => 
                    [count] => 6
                    [timeframe] => 0
                )

        )

    [debug] => 
    [filter] => the_content
    [message] => Notice (8): Undefined index: post_type
)

[16-May-2018 08:04:00 UTC] Array
(
    [error] => Notice
    [file] => /home/domain/wp-content/plugins/social-warfare/functions/widgets/SWP_Popular_Posts_Widget.php
    [line] => 369
    [context] => Array
        (
            [new_instance] => Array
                (
                    [title] => 
                    [count] => 6
                    [timeframe] => 0
                    [network] => totes
                    [showCount] => true
                    [countLabel] => Condivisioni
                    [thumbnails] => false
                    [thumb_size] => 100
                    [font_size] => 100
                    [style] => custom
                    [custom_bg] => #ffffff
                    [custom_link] => #000000
                )

            [old_instance] => Array
                (
                )

            [instance] => Array
                (
                    [title] => 
                    [count] => 6
                    [timeframe] => 0
                    [post_type] => 
                    [network] => totes
                    [showCount] => true
                    [countLabel] => Condivisioni
                    [style] => custom
                    [thumbnails] => false
                    [thumb_size] => 100
                )

        )

    [debug] => 
    [filter] => the_content
    [message] => Notice (8): Undefined index: thumb_width
)

[16-May-2018 08:04:00 UTC] Array
(
    [error] => Notice
    [file] => /home/domain/wp-content/plugins/social-warfare/functions/widgets/SWP_Popular_Posts_Widget.php
    [line] => 370
    [context] => Array
        (
            [new_instance] => Array
                (
                    [title] => 
                    [count] => 6
                    [timeframe] => 0
                    [network] => totes
                    [showCount] => true
                    [countLabel] => Condivisioni
                    [thumbnails] => false
                    [thumb_size] => 100
                    [font_size] => 100
                    [style] => custom
                    [custom_bg] => #ffffff
                    [custom_link] => #000000
                )

            [old_instance] => Array
                (
                )

            [instance] => Array
                (
                    [title] => 
                    [count] => 6
                    [timeframe] => 0
                    [post_type] => 
                    [network] => totes
                    [showCount] => true
                    [countLabel] => Condivisioni
                    [style] => custom
                    [thumbnails] => false
                    [thumb_size] => 100
                    [thumb_width] => 
                )

        )

    [debug] => 
    [filter] => the_content
    [message] => Notice (8): Undefined index: thumb_height
)
```

**Comment by ckmahoney** [comment]
Hello @Mte90 , 

Yes, we are aware of this issue and have been working diligently on resolving any and all PHP warnings/notices/errors. In fact, today we will be releasing 3.0.8. This version takes care of the issue your merge request suggest, as well as a few others our customers have been experiencing. 

Best,
Cortland Mahoney
- Social Warfare Development

**Comment by Mte90** [comment]
Seems that the 3.0.8 didn't fixed my issue -.-'

immagine
I am patching manually again and hope for a patch soon because I cannot get this kind of errors in page like 404.
Adda check if the object is a post type before to do anything :-)

**Comment by Mte90** [comment]
Update the pr with the last fix to this issues...

**Comment by Mte90** [comment]
Any updates for this one? I am quite annoyed to do that manually at every release.

**Comment by Mte90** [comment]
Another ping!

**Comment by Nicholas-Cardot** [comment]
We took a different approach to solving this, but it should be fully solved now. Thanks for letting us know about this!

**Pull request closed without merging**
